### ISSUE TITLE
为何github代码与npm上面的不同？

### ISSUE THREAD

**Issue by p2227** [teambition/volubile-ui#10]
package.json

```
"dependencies": {
    "flex.less": "^1.1.0",
    "gulp-coffee": "^2.3.1",
    "normalize.css": "^3.0.3",
    "open-sans-fontface": "1.4.0",
    "react": "^0.14.7",
    "roboto-fontface": "^0.4.2",
    "teambition-icon-fonts": "^0.72.2"
  },
```

但是npm上面的包是这样的

```
"flex.less":"git://github.com/codio/Flex.less.git"
```

因为公司网格限制了git://协议的访问
找了很久定位出来了，用代理把 http://registry.npmjs.org/volubile-ui 转到本地文本才解决。
发npm的文件与github文件最好一致吧？

**Comment by tiye** [comment]
No one is maintaining at this moment...

**Comment by Boshen** [comment]
我装了下 v0.1.2, package.json是对的呀 0.0

**Comment by Boshen** [comment]
但是registry确实是没更新，好奇怪。。 我看看

**Comment by Boshen** [comment]
应该没问题的， 试下把本地 cache 清下 `npm cache clean volubile-ui`

**Comment by p2227** [comment]
> No one is maintaining at this moment...

嗯，我大概知道这个项目目前的情况 。但也要提出来吧……

**Comment by p2227** [comment]
> 应该没问题的， 试下把本地 cache 清下 npm cache clean volubile-ui

解决，谢谢
